src/MediaSwap.Web/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MediaSwap.Core.Models;
using MediaSwap.Core.Services;
using MediaSwap.Web.ViewModels;
using MediaSwap.Web.Models;
namespace MediaSwap.Web.Controllers
{
    [Authorize]
    public class ItemController : Controller
    {

        IUserItemService IUserItemService = new UserItemService();
       


        public ActionResult Index()
        {
         
            return View(IUserItemService.GetItems(MediaSwapIdentity.Current.Id));
        }

        public ActionResult Movies()
        {
            return View(IUserItemService.GetItems(MediaSwapIdentity.Current.Id,"Movie"));
        }

        public ActionResult Games()
        {
            return View(IUserItemService.GetItems(MediaSwapIdentity.Current.Id, "Game"));
        }
        [HttpGet]
        public ActionResult AddGame()
        {
         

            var addItemViewModel = new AddItemViewModel();
            addItemViewModel.ItemTypeName = "Game";
            addItemViewModel.ItemTypes = new ItemTypeService().GetItemTypes("Game");
            return View("Add",addItemViewModel);
        }


        [HttpPost]
        public ActionResult AddItem(AddItemViewModel addItemViewModel)
        {
            IItemService _itemService = new ItemService();
            var existingItem = _itemService.Search(addItemViewModel.ItemName, addItemViewModel.ItemType.ItemTypeId).FirstOrDefault();
            if (existingItem == null)
            {
                existingItem  = new Item() { ItemName = addItemViewModel.ItemName, AmazonId = addItemViewModel.AmazonId, ItemType = addItemViewModel.ItemType };
                _itemService.SaveItem(existingItem);
            }
            IUserItemService.Add(existingItem.ItemId, MediaSwapIdentity.Current.Id);
            addItemViewModel.ItemTypes = new ItemTypeService().GetItemTypes(existingItem.ItemType.ItemTypeId);
            addItemViewModel.ItemTypeName = existingItem.ItemType.ItemTypeName;
            addItemViewModel.Status = "Item has been successfully added.";
            return View("Add",addItemViewModel);
        }

        [HttpGet]
        public ActionResult DeleteItem(int id)
        {
            IItemService _itemService = new ItemService();
            var item = _itemService.GetItem(id);
            return View(item);
        }

        [HttpPost]
        public ActionResult DeleteItem(Item item)
        {
            IItemService _itemService = new ItemService();

            try
            {
                _itemService.DeleteItem(item.ItemId);
                return RedirectToAction("Index");
            }
            catch (ApplicationException ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(item);
            }
        }
      
        [HttpGet]
        public ActionResult AddMovie()
        {

            var addItemViewModel = new AddItemViewModel();
            addItemViewModel.ItemTypeName = "Movie";
            addItemViewModel.ItemTypes = new ItemTypeService().GetItemTypes("Movie");
            return View("Add", addItemViewModel);
        }

      
    }
}

src/MediaSwap.Web/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;

using DotNetOpenAuth.Messaging;
using DotNetOpenAuth.OpenId;
using DotNetOpenAuth.OpenId.Extensions.SimpleRegistration;
using DotNetOpenAuth.OpenId.RelyingParty;

using MediaSwap.Core.Models;
using MediaSwap.Core.Services;
using System.Web.Routing;
using System.Web;
using MediaSwap.Web.Models;
namespace MediaSwap.Web.Controllers
{
    
    public class ProfileController : Controller
    {
        private static OpenIdRelyingParty _openId = new OpenIdRelyingParty();
        IProfileService IUserService;

        public ProfileController()
        {
            IUserService = new ProfileService();
        }
        [Authorize]
        public ActionResult Index()
        {
            return View(IUserService.GetUser((HttpContext.User.Identity as MediaSwapIdentity).Id));
        }
        [HttpGet]
        
        public ActionResult Create()
        {
            return View(new User() { });
        }

        [HttpPost]
        
        public ActionResult Create(User user)
        {
            if (ModelState.IsValid)
            {


                Session["SignupProfile"] = user;
            }

           return RedirectToAction("Authenticate");
        }
        
        public ActionResult Login()
        {
        
                return View();
           
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }

        [ValidateInput(false)]
        public ActionResult Authenticate(string returnUrl)
        {
            string googleOpenId = "https://www.google.com/accounts/o8/id";
            var response = _openId.GetResponse();

            if (response == null)
            {
                Identifier id;
                if (Identifier.TryParse(googleOpenId, out id))
                {
                    try
                    {
                        var request = _openId.CreateRequest(googleOpenId);

                        request.AddExtension(new ClaimsRequest()
                        {
                            Email = DemandLevel.Require
                        });

                        return request.RedirectingResponse.AsActionResult();
                    }
                    catch (ProtocolException ex)
                    {
                        ViewData["Message"] = ex.Message;
                        return View("Login");
                    }
                }
                else
                {
                    ViewData["Message"] = "Invalid identifier";
                    return View("Login");
                }
            }
            else
            {
                switch (response.Status)
                {
                    case AuthenticationStatus.Authenticated:
                        Session["FriendlyIdentifier"] = response.FriendlyIdentifierForDisplay;

                        var sreg = response.GetExtension<ClaimsResponse>();
                        
                        if (sreg != null)
                        {
                            User user = Session["SignupProfile"] as User;
                            if (user != null)
                            {
                                user.Email = sreg.Email;
                                user.Token = sreg.Email;

                                IUserService.SaveUser(user);
                            }
                            else
                            {
                                user = IUserService.GetUser(sreg.Email);
                                if (user == null)
                                {
                                    return RedirectToAction("Create");
                                }
                            }
                            // Do something with the values here, like store them in your database for this user.
                            var userData = string.Format("{0};{1};{2}", user.UserId, user.UserName, user.Email);
                            var ticket = new FormsAuthenticationTicket(
                                           2, // magic number used by FormsAuth
                                           response.ClaimedIdentifier, // username
                                           DateTime.Now,
                                           DateTime.Now.AddDays(30),
                                           true, // "remember me"
                                           userData);
                            
                            HttpCookie cookie = new HttpCookie(FormsAuthentication.FormsCookieName, FormsAuthentication.Encrypt(ticket));
                            if (ticket.IsPersistent)
                            {
                                cookie.Expires = ticket.Expiration;
                            }
                            Response.SetCookie(cookie);

                            Response.Redirect(Request.QueryString["ReturnUrl"] ?? "/");
      
                           
                        }
                        
                       
                        if (!String.IsNullOrEmpty(returnUrl))
                        {
                            return Redirect(returnUrl);
                        }
                        else
                        {
                            return RedirectToAction("Index", "Item");
                        }
                    case AuthenticationStatus.Canceled:
                        ViewData["Message"] = "Canceled at provider";
                        return View("Login");
                    case AuthenticationStatus.Failed:
                        ViewData["Message"] = response.Exception.Message;
                        return View("Login");
                }
            }

            return new EmptyResult();
        }
        [HttpGet]
        [Authorize]
        public ActionResult Edit()
        {

            return View(IUserService.GetUser(MediaSwap.Web.Models.MediaSwapIdentity.Current.Id));
        }

        [HttpPost]
        [Authorize]
        public ActionResult Edit(User user)
        {
            user.UserId = MediaSwap.Web.Models.MediaSwapIdentity.Current.Id;
            if (ModelState.IsValid)
            {
                IUserService.SaveUser(user);
            }
            return View("Index",user);
        }

        
      
        public string IsUserNameAvailable(string username)
        {
            var isAvailable = !IUserService.UserExists(username);
            return (isAvailable).ToString();
        }
 
    }
}

src/MediaSwap.Web/Controllers/QueueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MediaSwap.Core.Services;
using System.Net.Mail;
namespace MediaSwap.Web.Controllers
{
    public class QueueController : Controller
    {
        IQueueService IQueueService = new QueueService();
        //
        // GET: /Queue/
        [Authorize]
        public ActionResult Index()
        {
            var queueItems = IQueueService.GetQueue(MediaSwap.Web.Models.MediaSwapIdentity.Current.Id);
            return View(queueItems);
        }

        //protected override void OnAuthorization(AuthorizationContext filterContext)
        //{
        //    if (MediaSwap.Web.Models.MediaSwapIdentity.Current == null)
        //    {
        //        HttpContext.Response.AddHeader("REQUIRES_AUTH", "1");
        //    }
        //    base.OnAuthorization(filterContext);
        //}


        [Authorize]
        public ActionResult AddItem(int itemId)
        {
            IQueueService queueService = new QueueService();
            var user = MediaSwap.Web.Models.MediaSwapIdentity.Current;
            
            var itemService = new ItemService();
            var item = itemService.GetItemWithOwner(itemId);
            
            queueService.AddItemToQueue(user.Id, itemId, item.Users.FirstOrDefault().UserId);


            SmtpClient client = new SmtpClient();
            var message = string.Format("{0} has reserved {1}.", user.FriendlyName, item.ItemName);
            client.Send(new MailMessage("MediaSwap@CraftyCoders.com", item.Users.FirstOrDefault().Email) { Subject="MediaSwap Item Reserved", Body = message, IsBodyHtml = true });
           
            var queueItem = new MediaSwap.Web.ViewModels.SearchItemViewModel.ItemResult();
            queueItem.Status = MediaSwap.Core.Models.QueueStatus.Reserved;
            queueItem.Item  = itemService.GetItem(item.ItemId);
            return View("~/Views/Search/_ItemView.cshtml", queueItem);
        }

        public ActionResult Borrow(int queueId)
        {
            IQueueService queueService = new QueueService();
            queueService.BorrowQueueItem(queueId);
            return RedirectToAction("Index");
        }

        public ActionResult Return(int queueId)
        {
            IQueueService queueService = new QueueService();

            queueService.ReturnQueueItem(queueId);
            return RedirectToAction("Index");
        }

        public ActionResult Remove(int queueId)
        {
            IQueueService queueService = new QueueService();

            queueService.RemoveItemFromQueue(queueId);
            return RedirectToAction("Index");
        }
    }
}

src/MediaSwap.Web/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

using MediaSwap.Web.ViewModels;
using MediaSwap.Core.Services;

namespace MediaSwap.Web.Controllers
{
    [Authorize]
    public class SearchController : Controller
    {
        const int numPerPage = 15;

        public ActionResult Index()
        {
            SearchItemViewModel searchItemViewModel = new SearchItemViewModel();
            ItemService iss = new ItemService();
            var queueItems = new QueueService().GetQueue(MediaSwap.Web.Models.MediaSwapIdentity.Current.Id);

            searchItemViewModel.ItemResults = iss.Search("").Select(s => new SearchItemViewModel.ItemResult() { Item = s }).ToList();
            foreach (var queueItem in queueItems)
            {
                var searchItem = searchItemViewModel.ItemResults.FirstOrDefault(i => i.Item.ItemId == queueItem.ItemId);
                if (searchItem != null)
                {
                    searchItem.Status = queueItem.Status;
                }
            }
            return View(searchItemViewModel);
        }

        [HttpPost]
        public ActionResult Index(string search)
        {
            SearchItemViewModel searchItemViewModel = new SearchItemViewModel();
            ItemService iss = new ItemService();
            var queueItems = new QueueService().GetQueue(MediaSwap.Web.Models.MediaSwapIdentity.Current.Id);

            searchItemViewModel.ItemResults = iss.Search(search).Select(s=>new SearchItemViewModel.ItemResult(){ Item  = s}).ToList();
            foreach (var queueItem in queueItems)
            {
               var searchItem =  searchItemViewModel.ItemResults.FirstOrDefault(i => i.Item.ItemId == queueItem.ItemId);
               if (searchItem != null)
               {
                   searchItem.Status = queueItem.Status;
               }
            }
            return View(searchItemViewModel);
        }
    }
}

src/MediaSwap.Web/Views/Shared/_Layout.cshtml

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/bootstrap/css/bootstrap.min.css")"  rel="stylesheet"
        type="text/css" />
    
    <style type="text/css">
        html, body
        {
            background: #eee;
            margin-top: 20px;
        }
        body
        {
            
        }
        input[type="text"], input[type="number"], select
        {
           
        }
        .content
        {
            background-color: #fff;
            padding: 20px;
            margin: 0 -20px;
            min-height: 500px;
            -webkit-border-radius: 0 0 5px 5px;
            -moz-border-radius: 0 0 5px 5px;
            border-radius: 0 0 5px 5px;
            -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.15);
            -moz-box-shadow: 0 1px 2px rgba(0,0,0,.15);
            box-shadow: 0 1px 2px rgba(0,0,0,.15);
        }
      
        
        .container > footer
        {
            color: #777;
            margin: 0;
            border-top: 0px;
            padding-bottom: 10px;
        }
        /* Styles for validation helpers
-----------------------------------------------------------*/
        .field-validation-error
        {
            color: #ff0000;
        }
        
        .field-validation-valid
        {
            display: none;
        }
        
        .input-validation-error
        {
            border: 1px solid #ff0000;
            background-color: #ffeeee;
        }
        
        .validation-summary-errors
        {
            font-weight: bold;
            color: #ff0000;
        }
        
        .validation-summary-valid
        {
            display: none;
        }
        footer {
            margin-top: 17px;
            padding-top: 17px;
            border-top: 1px solid #EEE;
        }
    </style>
    @RenderSection("style", required: false)
    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.7.min.js" type="text/javascript"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"
        type="text/javascript"></script>
         <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
</head>
<body>
    <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="brand" href="/">Media Swap</a>
        <ul class="nav">
         
                   
                    <li><a href="@Url.Action("Index", "Item")">My Media</a> </li>
                    <li><a href="@Url.Action("Index","Queue")">My Queue</a></li>
                    <li><a href="@Url.Action("Index", "Search")">Search Media</a></li>
        </ul>
        <ul class="nav pull-right">
                  @if (!HttpContext.Current.User.Identity.IsAuthenticated)
                  {
                  <li>@Html.ActionLink("Login", "Login", "Profile")</li>
                  }
                  else
                  {
                     <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" style="background-image:url(@GravatarHelper.GravatarImageString(MediaSwap.Web.Models.MediaSwapIdentity.Current.EmailAddress,40,"")); background-repeat:no-repeat"> <span style="display:inline-block; margin-left:40px">   @MediaSwap.Web.Models.MediaSwapIdentity.Current.FriendlyName</span><span class="caret"></span></a>  <ul class="dropdown-menu">
      <li>@Html.ActionLink("View Profile","Index","Profile")</li>
    
      <li class="divider"></li>
      <li>@Html.ActionLink("Logout","Logout","Profile")</li>
    </ul></li>
                  }
                 
                </ul>
                </div>
    </div><!-- /navbar-inner -->
  </div><!-- /navbar -->

    <div class="container">
        <div class="content">
          @MvcMiniProfiler.MiniProfiler.RenderIncludes()
            @RenderBody()
        </div>
        <footer>
      <p>
        Made in a Hackathon.
      </p>
    </footer>
    </div>
    @RenderSection("javascript", required: false)
    <script type="text/javascript" src="@Url.Content("~/Content/bootstrap/js/bootstrap.min.js")"  >
     
    </script>
</body>
</html>